build:
  stage: build
  tags:
    - suparmucac1
  script: 
    - cd dlmtesting
    - docker-compose build

build:
  stage: build
  tags:
    - suparmucac2
  script: 
    - cd dlmtesting
    - docker-compose build
    
build:
  stage: build
  tags:
    - suparmucac3
  script: 
    - cd dlmtesting
    - docker-compose build