stages:
  - build
  - run

variables:
  CONTAINER_NAME: "qtbase"
  CONTAINER_PORT: "3507"

build:
  stage: build
  tags:
    - suparmucac2
  script: 
    - cd $CONTAINER_NAME
    - docker-compose build
    
#run:
#  stage: run
#  tags:
#    - suparmucac2
#  script: 
#    - cd qtwebgl
#    - docker-compose up -d --force-recreate