build:suparmucac1:
  stage: build
  tags:
    - suparmucac1
  script: 
    - cd dlmtesting
    - docker-compose build

build:suparmucac2:
  stage: build
  tags:
    - suparmucac2
  script: 
    - cd dlmtesting
    - docker-compose build
    
build:suparmucac3:
  stage: build
  tags:
    - suparmucac3
  script: 
    - cd dlmtesting
    - docker-compose build