stages:
  - build_base
  - build
  - run

################################## Qt5 Base ###################################

build_base:suparmucac1:qtbase:
  stage: build_base
  tags:
    - suparmucac1
  script: 
    - cd qtbase
    - docker build --tag qtbase_image .
  
build_base:suparmucac2:qtbase:
  stage: build_base
  tags:
    - suparmucac2
  script: 
    - cd qtbase
    - docker build --tag qtbase_image .

build_base:suparmucac3:qtbase:
  stage: build_base
  tags:
    - suparmucac3
  script: 
    - cd qtbase
    - docker build --tag qtbase_image .

################################## Cuda XRDP ###################################

build_base:suparmucac1:xrdpcuda:
  stage: build_base
  tags:
    - suparmucac1
  script: 
    - cd xrdpcuda
    - docker build --tag xrdpcuda_image .

build_base:suparmucac2:xrdpcuda:
  stage: build_base
  tags:
    - suparmucac2
  script: 
    - cd xrdpcuda
    - docker build --tag xrdpcuda_image .
    
build_base:suparmucac3:xrdpcuda:
  stage: build_base
  tags:
    - suparmucac3
  script: 
    - cd xrdpcuda
    - docker build --tag xrdpcuda_image .

################################## WebGL ######################################

build:suparmucac1:qtwebgl:
  stage: build
  tags:
    - suparmucac1
  script: 
    - cd qtwebgl
    - docker build --tag qtwebgl_image .
    
build:suparmucac2:qtwebgl:
  stage: build
  tags:
    - suparmucac2
  script: 
    - cd qtwebgl
    - docker build --tag qtwebgl_image .
    
build:suparmucac3:qtwebgl:
  stage: build
  tags:
    - suparmucac3
  script: 
    - cd qtwebgl
    - docker build --tag qtwebgl_image .