stages:
  - build_base
  - build
  - run

build_base:qtbase:
  stage: build_base
  tags:
    - suparmucac2
  script: 
    - cd qtbase
    - docker build --tag qtbase_image .

build:qtwebgl:
  stage: build
  tags:
    - suparmucac2
  script: 
    - cd qtwebgl
    - docker-compose build
    
