stages:
  - build_base
  - build
  - run

build_base:qtbase:
  stage: build
  tags:
    - suparmucac2
  script: 
    - cd qtbase
    - docker-compose build

build:qtbase:
  stage: build
  tags:
    - suparmucac2
  script: 
    - cd qtwebgl
    - docker-compose build
    
run:
  stage: run
  tags:
    - suparmucac2
  script: 
    - cd qtwebgl
    - docker-compose up -d --force-recreate