version: "2"
services:

  gitlab:
    build: .
    image: 'gitlab-ce'
    network_mode: "bridge"
    restart: always
    hostname: 'git.emb-lab.org'
    container_name: gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://git.emb-lab.org'
    ports:
      - 2222:22/tcp
      - 80:80/tcp
    volumes:
      - '/srv/docker/volumes/gitlab/config:/etc/gitlab'
      - '/srv/docker/volumes/gitlab/logs:/var/log/gitlab'
      - '/srv/docker/volumes/gitlab/data:/var/opt/gitlab'
      - '/srv/backups/gitlab:/srv/backup'
      - '/srv/lfs-storage:/srv/lfs-storage'
