version: "2"

volumes:
  nvidia_driver_367.35:
      external: true

services:
    dlmtesting:
        build: .
        container_name: dlmtesting
        devices:
            - /dev/nvidiactl
            - /dev/nvidia-uvm
            - /dev/nvidia-uvm-tools
            - /dev/nvidia0
            - /dev/nvidia1
        volumes:
            - nvidia_driver_367.35:/usr/local/nvidia:ro
#            - ./Projects:/home/desktop/Persistent
        ports:
            - 141.19.87.231:3400:3389/tcp

