version: "2"

volumes:
  nvidia_driver_367.35:
      external: true

services:
    dlmtesting:
        build: .
        container_name: dlmtesting
        devices:
            - /dev/nvidiactl
            - /dev/nvidia-uvm
            - /dev/nvidia0
        volumes:
            - nvidia_driver_367.35:/usr/local/nvidia:ro
        ports:
            - 141.19.87.231:3400:3389/tcp

