version: "2"
services:
    qtbase:
        build: .
        image: qtbase_image
        container_name: qtbase
        environment:
            - CONTAINER=QTBASE
        cpuset: 0-16
        working_dir: /root

