version: "2"

volumes:
  nvidia_driver_367.35:
      external: true

services:
    work:
        build: .
        container_name: work
        devices:
            - /dev/nvidiactl
            - /dev/nvidia-uvm
            - /dev/nvidia0
        volumes:
            - nvidia_driver_367.35:/usr/local/nvidia:ro
            - /home/pbialecki/work/Projects:/home/desktop/Projects
        ports:
            - 141.19.87.231:3392:3389/tcp

